export const MOVIE_BASE_URL=process.env["MOVIE_BASE_URL"];
export const MOVIE_ACCESS_TOKEN=process.env["MOVIE_ACCESS_TOKEN"];
export const NEXT_PUBLIC_IMAGE_BASE_URL=process.env["NEXT_PUBLIC_IMAGE_BASE_URL"];


console.log("MOVIE_BASE_URL:", MOVIE_BASE_URL);
console.log("MOVIE_ACCESS_TOKEN:", MOVIE_ACCESS_TOKEN);
console.log("NEXT_PUBLIC_IMAGE_BASE_URL:", NEXT_PUBLIC_IMAGE_BASE_URL);